language: node_js
node_js:
- node
- 6
script:
- npm test
- codecov
deploy:
  provider: npm
  on:
    tags: true
  email: geo-dpes@google.com
  api_key:
    secure: KF5FsXJP0D121LkDISMV0xnNrknRitIBrYZgTiPx/RrN7Y3MqnCQVVUuuPCyJO7aT8+NwfgkBoaeYEjh5jHktJ3TZHBTEce1+MFP77299VO7tdLW9ht6+fEeptb4W/XjMK78oncsM+90sCxiWyk1TGbZ3+uQIxSla6tIk0/2cxhNovsCidm74csqWlS8qMHUCyWddg7md30FPZHK5WtZwA1dtVpIwwrvY60eW4QGdv45KFw74X4WhHGbQ7ug/brcStwW3PPyWlk8oqCYxyh2x+uNtv4KkQgDabfRLXrLhX1oxRvJ9uAl/kd5kiIEoe07dnSjHYMEwyIuqoO6jKoZZTCTlxKONoNrxW4BskuKqU5aqsWpJNaQI4CC8vU/tvLwOhkSY5oFN9U9+D+BcSnhI5KiU4QSoFImW0PXSK4xFDaExej2xVGiO6eW0lNusUzKH7DmnG1T03F4zMdQZ2lgUxWtz4EeaMNBXORU3NQBwm5ttO8MGaT+KuYPCOYnrb8mhNhmkj4a3Fs+LoV3bMd6g6oJJQaOBFprBYSBfYYJcX9zW8R+IOth5L4w7snu0fBOgVT2exFXz8JRl5yeXQxiWuMSwkeEwIRn3AZwh52RRySxcADKn5n724lb4npLgbGuIQQ+KaoKcJY6R9/u1RVw2Dg2A3dVrUVVnAI2kKs2PHY=
env:
  global:
    secure: ZTVv7iYQ4PK13kwxKcfNYvaI+kWguRHYSY0mJeiFbbrqt1haRbCddkcloXYMf5C5MhOT8YYDTu52LufkUdfL0fMNBoWK6OHxjyoGYAydDUx+K7sUYQOwHgIjYnvKtf9O42WYk6DeguKjcOox25zlUb53QprTORp2vwqaRQgw8Dt59lGMTDhtkiOZd++maTg5zXlteys5R74b+prEgAS0xZ6TghOat6QrzWEDzTUAiIpLcPv5lCo513zN52c2/CKXjnBWyCD9rIgzP0Xll7pGVWikgXITIijeS7LSfayMHekBykVX6QDy1vZiU1KftMVwT2tAfhd6j7uzWknW/M/TMSKifqstrDQtBcQouWGgMBObxXzBZr6d3VPSkwgaeyc91fTDsy10ETzUOsQF0yywLpApjlTxQDpqPDoLMF/VuephNs4sxjoALBNM5MJ6ccMtLut8VvfmWWOghaRZLg2I0QmFWEgbecFPCkAdH4wlM91yu8+JnN+ROHGQulQ646IjABy/TF03GUxY0986vkUpJrXNRtWU6kPId5h2CAm+Yu9M5uBmQPbHxzW0lnEORQmxKUm6uZm+tkoIc5U54SuQgn8yxljTgRR0Jj5cy6JObkeDiznGnwYwQLCkog0YNFElcwv9yhc9+dKP6D6yoDiBjH1anRzRjdhLqmZi8S4mtQ0=
