name: Release
on:
  push:
    branches: [ master ]
jobs:
  release:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }} 
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run test:all
      env:
        GOOGLE_MAPS_API_KEY: ${{ secrets.SYNCED_GOOGLE_MAPS_API_KEY_SERVICES }}
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      if: success()
      with:
        extra_plugins: |
          "@semantic-release/commit-analyzer"
          "@semantic-release/changelog"
          "@semantic-release/release-notes-generator"
          "@semantic-release/git
          "@semantic-release/github
          "@semantic-release/npm
      env:
        GH_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
        NPM_TOKEN: ${{ secrets.SYNCED_NPM_TOKEN }}
